apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-deployment
  labels:
    app: item
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item
  template:
    metadata:
      labels:
        app: item
    spec:
      volumes:
        - name: postgres-volume

      containers:
        - name: item
          image: gamorim/itemservice:latest
          env:
          - name: DB_CONNECTION_STRING
            value: "Host=postgres-service;Database=postgres;Username=postgres;Password=mysecretpassword"
          ports: 
          - containerPort: 80